### ISSUE TITLE
Bars to continue like red bar in footer

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/firemandryerman.com#1]
Bars to continue like red bar in footer. Also, can the area behind all banners be 2f3e4f?
![screen shot 2017-01-18 at 11 53 07 am](https://cloud.githubusercontent.com/assets/20116181/22076447/b2213746-dd75-11e6-8634-c1c6d6d75ef3.png)

I imagine this means I need to resend all photos. What size would you like them?

**Comment by kelly-wolfe** [comment]
I mean, since I have to send all new images anyway, I might as well send them the size you want. So double for retina or whatever?

**Comment by vcfolger** [comment]
Also, "Services" header needs to be formatted like About Us, etc. (in black bar with red line)

**Comment by joshbolinger** [comment]
could you check here

http://firemandryerman.com/

Also, how do you want to handle the hero section and title?

**Comment by kelly-wolfe** [comment]
I'm sorry I wasn't more clear. I want hero and red bar beneath treated the same. Continue all the way and blue background.

**Comment by kelly-wolfe** [comment]
This one still has white background. 
![screen shot 2017-01-24 at 3 56 37 pm](https://cloud.githubusercontent.com/assets/20116181/22268618/ca04f7b2-e24d-11e6-9dee-2776bf5b1fec.png)

**Comment by vcfolger** [comment]
Right. Should the entire site also be left aligned so the background is all to the right? That would avoid the weird negative space to the left of the hero banners (as here).
![screen shot 2017-01-24 at 4 44 02 pm](https://cloud.githubusercontent.com/assets/20050245/22270250/571e0ce6-e254-11e6-9320-fb19b647f985.png)

**Comment by kelly-wolfe** [comment]
I would be interested to see how that looks. I imagine it's an easy change?

**Comment by joshbolinger** [comment]
fixed home banner, and not sure what you mean about left aligned

**Comment by vcfolger** [comment]
By left aligned, just that the background of the site is all to the right, instead of extending out on both sides when the window is large enough. That way the banner images and the website in general always sticks to the left edge of the window...is that done? Call me if you still don't know what I mean
