### ISSUE TITLE
About Us photo

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/firemandryerman.com#10]
So the photo of the Ketchum fam is very cute and worked for me when you had it in a design comp, but on the site it seems a little off. A big header "About Us" and a photo of a family...I almost expect Lindsay to be involved in the company or something...does this photo seem out of place to you? Maybe a photo of Brett working on a dryer OR in full fireman gear would be more appropriate?

**Comment by kelly-wolfe** [comment]
I just picked it for FPO, but they like it. I think Linds probably loves having her pic on there...But yes, I know what you mean.

**Comment by vcfolger** [comment]
I showed Brett and asked him--he still likes it. But notice there's a ghost of his shirt to the left...is that ixed in the latest image you sent Josh?

**Comment by kelly-wolfe** [comment]
Yeah, I fixed that :)




_______________________________________________________
KELLY WOLFE  |  Art Director+  |  512.785.6623  |  wolfe-design.com <http://wolfe-design.com/>

**Comment by joshbolinger** [comment]
done, cant close ticket
