### ISSUE TITLE
Header font

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/firemandryerman.com#11]
The header font looks a little generic -- does it need to be swapped for something specific to match comps? Or is this close enough? See example below with comps on the left, site on the right.
![screen shot 2017-01-18 at 11 45 43 pm](https://cloud.githubusercontent.com/assets/20050245/22095175/56cbec3e-ddd8-11e6-847a-d737a1c32bc4.png)

**Comment by joshbolinger** [comment]
Kelly used fonts that are not web friendly, so she game me some alternate web fonts to use
