### ISSUE TITLE
Book Now button bevel treatment

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/firemandryerman.com#12]
Should the Book Now Button (in header and under "Contact Us") have a bevel effect like in comps? (see screenshot with comps on left, site on right)

![screen shot 2017-01-18 at 11 49 04 pm](https://cloud.githubusercontent.com/assets/20050245/22095214/bbfb39e8-ddd8-11e6-88df-89f5f3e9e662.png)

**Comment by joshbolinger** [comment]
I cant create a bevel like that without using an image and didnt feel like it added to the site or matched anything else, so I took it out

**Comment by vcfolger** [comment]
Kelly, thoughts?

**Comment by kelly-wolfe** [comment]
Thats fine. We actually added it b/c of a misunderstanding with client.
