### ISSUE TITLE
Photo captions left out on home page

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/firemandryerman.com#4]
If it is too hard to do it like it was done on my psd, just do small copy below pic instead.

**Comment by joshbolinger** [comment]
I left this out because it lacked copy and didnt seem that important. Do we have the new copy?

**Comment by vcfolger** [comment]
I don't have any idea what these captions are or what they look like. I think it was discussed and implemented between Kelly and Brett. Kelly, could you post screen captures here so I know what you mean?

**Comment by kelly-wolfe** [comment]
Its just smaller itallic copy under the photos. He only actually gave me copy for the bottom one.  Just put place holder copy for the other.

**Comment by kelly-wolfe** [comment]
I meant only for the photos on homepage.

**Comment by vcfolger** [comment]
Still don't know what the copy is/looks like...screenshot of psd pls?

**Comment by kelly-wolfe** [comment]
Oh, yeah, I forgot you don't have the most recent. Sbt
![screen shot 2017-01-25 at 9 23 30 am](https://cloud.githubusercontent.com/assets/20116181/22296529/0e5d0d86-e2e0-11e6-9c16-2c56db71b5fe.png)

**Comment by vcfolger** [comment]
Client decided no captions
