### ISSUE TITLE
Replace body copy

### ISSUE THREAD

**Issue by kelly-wolfe** [vcfolger/firemandryerman.com#5]
It is basically the right font, but I think the problem is that it doesn't come in any different weights.  As I understand, its pretty easy to change in style sheets. Yes? 
Maybe try this google font since it has a lot of weight options.   **Source Sans Pro**

**Comment by vcfolger** [comment]
Kelly, I don't understand what you mean here--are you saying that all body copy font needs to be replaced with Source Sans Pro?

**Comment by kelly-wolfe** [comment]
Yes and formatted like the psd example. But to be honest, I am open to suggestion on fonts. If Josh has favorite san serif he uses, I'm down.

**Comment by joshbolinger** [comment]
done
