### ISSUE TITLE
Menu issues

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/firemandryerman.com#6]
The design file was probably not synched up with approved copy. There should be a "home" tab. Services should be "Dryer Vent Services". Otherwise, looks good except that there is a white vertical line missing between "Services" and "About Us" when the window is pulled wide (full-screen on my laptop but I have a smallish laptop.

(approved menu from copy)
Home
Dryer Vent Services
About Us
Contact Us
Book Now
![screen shot 2017-01-18 at 10 53 24 pm](https://cloud.githubusercontent.com/assets/20050245/22094211/5eb520a2-ddd1-11e6-9d87-96169ad3f0c0.png)

**Comment by joshbolinger** [comment]
This is going to make the menu too long, its already pushing it

**Comment by vcfolger** [comment]
Josh, I was thinking this would be a good boost for SEO, Dryer Vent seems short enough to fit --- I'll defer to you but wanted to push the issue one more time to make sure you think it's worth cutting it to "Services"

**Comment by kelly-wolfe** [comment]
I could have sworn I adjusted. Whoops. If home needs to be house icon, that works for me.

**Comment by vcfolger** [comment]
I'm okay with the house icon unless client requests a change. Still want to hear from Josh on "Dryer Vent Services"`

**Comment by joshbolinger** [comment]
I added the house icon and added alt and title tags to the Services link

To make this all fit, I had to reduce the font size 5px FYI

**Comment by vcfolger** [comment]
Per client feedback, please change house icon in top menu to the word "home"

**Comment by joshbolinger** [comment]
done
