### ISSUE TITLE
Services/Copy change under three steps

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/firemandryerman.com#9]
Instead of current red copy:
The final part of our service is what sets Fireman Dryerman apart from other companies who offer a similar service.

Use this:
Our focus on fire safety sets Fireman Dryerman apart.

Add body copy underneath (regular sized black copy):
Other companies who offer a similar service usually do not take the extra step to clean difficult-to-access parts of your dryer where fires can start.

**Comment by kelly-wolfe** [comment]
Also, don't forget to add the other images in the updated psd.

**Comment by joshbolinger** [comment]
done
